import type { Studio } from './types';

export const mockStudios: Studio[] = [
  {
    id: '1',
    name: 'Crystal Sound Studios',
    city: 'Los Angeles, CA',
    distance: 1.2,
    rating: 4.8,
    reviewCount: 247,
    tags: ['Soundproof', 'WiFi', 'Engineer on site'],
    imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=300&fit=crop',
    pricePerHour: 65,
    nextAvailableSlot: 'Today at 4:00 PM',
    description: 'Professional recording studio with top-tier equipment',
    featured: true,
  },
  {
    id: '2',
    name: 'Urban Photo Loft',
    city: 'Los Angeles, CA',
    distance: 2.1,
    rating: 4.6,
    reviewCount: 189,
    tags: ['Natural light', 'Backdrop selection', 'Parking'],
    imageUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=300&fit=crop',
    pricePerHour: 50,
    nextAvailableSlot: 'Today at 2:00 PM',
    description: 'Bright loft with natural lighting for photo shoots',
  },
  {
    id: '3',
    name: 'Neon Dreams Studio',
    city: 'Hollywood, CA',
    distance: 3.5,
    rating: 4.9,
    reviewCount: 312,
    tags: ['Vocal booth', 'Mixing suite', 'Lounge'],
    imageUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69b13d835?w=400&h=300&fit=crop',
    pricePerHour: 85,
    nextAvailableSlot: 'Tomorrow at 10:00 AM',
    description: 'State-of-the-art recording complex',
    featured: true,
  },
  {
    id: '4',
    name: 'Pixel Perfect Studios',
    city: 'Santa Monica, CA',
    distance: 4.2,
    rating: 4.7,
    reviewCount: 156,
    tags: ['Green screen', '4K lighting', 'Sound design'],
    imageUrl: 'https://images.unsplash.com/photo-1521310503527-33f90a0a0adc?w=400&h=300&fit=crop',
    pricePerHour: 75,
    nextAvailableSlot: 'Today at 6:00 PM',
    description: 'Video production studio with professional equipment',
  },
  {
    id: '5',
    name: 'Echo Chamber',
    city: 'Downtown LA',
    distance: 0.8,
    rating: 4.5,
    reviewCount: 98,
    tags: ['Rehearsal space', 'PA system', 'Instruments'],
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop',
    pricePerHour: 45,
    nextAvailableSlot: 'Today at 3:00 PM',
    description: 'Full-service rehearsal and recording studio',
  },
  {
    id: '6',
    name: 'Sunset Acoustics',
    city: 'West Hollywood, CA',
    distance: 2.8,
    rating: 4.8,
    reviewCount: 224,
    tags: ['Acoustically tuned', 'Lounge area', 'Parking'],
    imageUrl: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=300&fit=crop',
    pricePerHour: 70,
    nextAvailableSlot: 'Tomorrow at 1:00 PM',
    description: 'Carefully designed acoustic recording space',
  },
  {
    id: '7',
    name: 'Innovation Hub',
    city: 'Pasadena, CA',
    distance: 8.5,
    rating: 4.4,
    reviewCount: 67,
    tags: ['Tech setup', 'High-speed internet', 'Podcast-ready'],
    imageUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=400&h=300&fit=crop',
    pricePerHour: 40,
    nextAvailableSlot: 'Today at 5:00 PM',
    description: 'Modern podcast and streaming studio',
  },
  {
    id: '8',
    name: 'Golden Hour Spaces',
    city: 'Santa Monica, CA',
    distance: 4.9,
    rating: 4.7,
    reviewCount: 201,
    tags: ['Day light', 'Backdrop studio', 'Makeup chair'],
    imageUrl: 'https://images.unsplash.com/photo-1511671782486-a01980e01a18?w=400&h=300&fit=crop',
    pricePerHour: 55,
    nextAvailableSlot: 'Today at 1:00 PM',
    description: 'Premium photography studio with premium backdrops',
  },
];
